### PR TITLE
115 feature add new base location with google geolocation

### LINKED ISSUE #115: Feature: Add New Base Location with Google Geolocation
# [Feature] Add New Base Location with Google Geolocation
Description: Implement location search and addition using Google's reverse geolocation API
## Problem
Users need a way to easily add new base locations on the Dashboard page without manuallry entering coordinates.
## Proposed Solution
Add a location search feature that:
1. Integrates Google's reverse geolocation API
2. Allows users to search by address/place name
3. Automatically fills in coordinates and location details
## Code for Proposed Implementation
```javascript
const AddLocationForm = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [location, setLocation] = useState(null);

  const handleSearch = async () => {
    try {
      const response = await googleGeocoder.geocode({ address: searchQuery });
      const { lat, lng } = response.results[0].geometry.location;
      setLocation({
        latitude: lat,
        longitude: lng,
        address: response.results[0].formatted_address
      });
    } catch (error) {
      console.error('Geocoding error:', error);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input 
        type="text"
        value={searchQuery}
        onChange={(e) => setSearchQuery(e.target.value)}
        placeholder="Search location..."
      />
      <button type="button" onClick={handleSearch}>
        Search
      </button>
      {location && (
        <LocationDetails location={location} />
      )}
    </form>
  );
};
```
## Additional Context
- Need to handle API rate limiting

### PR DESCRIPTION
**Pull request by joshmfrancis**
@connorzittrauer Pwease merge in 🥺, made addition of Add Location Button to all pages and fixed up some css on my page that was bothering me.

### CODE REVIEW

File: frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+        userId: user.id,
+        name: selectedPlace.name,
+        latitude: selectedPlace.geometry.location.lat(),
+        longitude: selectedPlace.geometry.location.lng(),
+        isFavorite,
+      };
+
+      console.log('Sending location data:', locationData);
+
+      const response = await fetch('http://localhost:5001/api/locations', {
```
Comment (connorzittrauer) [inline frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js]: Again, use string interpolation like show in the comment above
await axios.post(`${REACT_APP_API_URL}/api/locations`,

File: frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js [hunk 2]
```diff
@@ -0,0 +1,250 @@
...
+
+    const loadGoogleMaps = async () => {
+      try {
+        setIsLoading(true);
+        setError('');
+
+        // Check if script is already loaded
+        if (!window.google) {
+          const script = document.createElement('script');
+          script.src = `https://maps.googleapis.com/maps/api/js?key=${process.env.REACT_APP_GOOGLE_MAPS_API_KEY}&libraries=places`;
```
Comment (connorzittrauer) [inline frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js]: Don't embed the environment variable key directly the URL string. Use a global variable defined at the top. Look at how Weather.js does it:

```javascript
// Declare URL at the top of file with other constants
const REACT_APP_API_URL = process.env.REACT_APP_API_URL;
...
// Like this
await axios.post(`${REACT_APP_API_URL}/api/locations`,
```

File: frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+    // Clear selected place when user starts typing again
+    if (selectedPlace) {
+      setSelectedPlace(null);
+    }
+  };
+
+  if (!isOpen) return null;
+
+  return (
+    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
```
Comment (connorzittrauer) [inline frontend/src/components/specific/AddLocationPopup/AddLocationPopup.js:135]: I thought we were not using inline CSS so we could separate concerns?

**Review by connorzittrauer — CHANGES_REQUESTED** [review]
